name: deploy to azure
on: workflow_dispatch
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install
      - run: yarn run build
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./public" # App source code path
          # api_location: "" # Api source code path - optional
          # output_location: "/" # Built app content directory - optional
          skip_app_build: true
          skip_api_build: true
          ###### End of Repository/Build Configurations ######
      # - uses: actions/upload-pages-artifact@v1
      #   with:
      #     path: ./public
